format = "$directory$git_branch$git_status$line_break$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold mauve)"

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
style = "bold purple"
